[package]
name = "my_os"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.9.8"
x86_64 = "0.14.2"
linked_list_allocator = "0.10"
volatile = "0.2.6"

[rust-analyzer.checkOnSave]
allTarget = false
