[package]
name = "ef_os"
version = "0.1.0"
edition = "2021"

[dependencies]
bootloader = "0.9.8"
linked_list_allocator = "0.10"
lazy_static = {version="1.4", features = ["spin_no_std"]}
spin = "0.5"
macros = {path = "macros"}

